export const initialForms = [
  {
    // custom_values: [],
    type: 'hashtag',
    type_id: 1,
    type_title: 'Who are you?',
    type_value: 'user_types',
    values: [
      { id: 1, value: 'Founder' },
      { id: 2, value: 'Investor' },
    ],
    // is_active: true,
    // order: 1
  },
  {
    // custom_values: [],
    type: 'input',
    type_id: 2,
    type_title: 'Name/Company names',
    type_value: 'name',
    values: [],
    // is_active: true,
    // order: 2,
  },
  {
    // custom_values: [],
    type: 'hashtag',
    type_id: 3,
    type_title: 'Industries',
    type_value: 'industries',
    values: [
      { id: 1, value: 'FoodTech' },
      { id: 2, value: 'EdTech' },
      { id: 3, value: 'Crypto' },
      { id: 4, value: 'TravelTech' },
      { id: 4, value: 'Blockchain' },
      { id: 4, value: 'AI' },
      { id: 4, value: 'Gaming' },
      { id: 4, value: 'SocialMedia' },
      { id: 4, value: 'Mobility' },
      { id: 4, value: 'FashionTech' },
      { id: 4, value: 'E-commerce' },
    ],
    // is_active: true,
    // order: 3,
  },
  {
    // custom_values: [],
    type: 'hashtag',
    type_id: 4,
    type_title: 'Business model',
    type_value: 'business_models',
    values: [
      { id: 1, value: 'B2B' },
      { id: 2, value: 'B2C' },
    ],
    // is_active: true,
    // order: 4,
  },
  {
    // custom_values: [],
    type: 'hashtag',
    type_id: 5,
    type_title: 'Project stage',
    type_value: 'project_stages',
    values: [
      { id: 1, value: 'Idea' },
      { id: 2, value: 'MVP' },
      { id: 2, value: 'FirstSale' },
    ],
    // is_active: true,
    // order: 4,
  },
  {
    // custom_values: [],
    type: 'textarea',
    type_id: 6,
    type_title: 'Description',
    type_value: 'description',
    values: [],
    // is_active: true,
    // order: 4,
  },
  {
    // custom_values: [],
    type: 'donuts',
    type_id: 7,
    type_title: 'Donuts',
    type_value: 'donuts',
    values: [],
    // is_active: true,
    // order: 4,
  },
  {
    // custom_values: [],
    type: 'hashtag',
    type_id: 8,
    type_title: 'Geography',
    type_value: 'geography',
    values: [
      { id: 1, value: 'LocalBusiness' },
      { id: 2, value: 'GlobalStartup' },
    ],
    // is_active: true,
    // order: 4,
  },
];

export const initialCurrencies = [
  { id: 1, currency: 'USD' },
  { id: 2, currency: 'EUR' },
  { id: 3, currency: 'RUB' },
  { id: 4, currency: 'GBP' },
  { id: 5, currency: 'CNY' },
  { id: 6, currency: 'JPY' },
];
